### ISSUE TITLE
Always return HTTP 200 from check endpoint

### ISSUE THREAD

**Issue by severinraez** [puzzle/statuscope#1]
Turns out Icinga can monitor whether `.state == 'ok'` in the JSON payload, we don't have to return a non-200 status if the checked subject is broken (406 in our case).

**Comment by severinraez** [comment]
Sorry, did not see this. I already coordinated with /sys to set up checks expecting HTTP 200. Also https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406 seems to have a pretty narrow definition, but I don't know whether mozilla preaches the canonical gospel here... I am open to changing this, for now I am happy that it works.

**Comment by kronn** [comment]
Well, as long as real error-conditions (most notably 404) are handled properly, I am fine with this change. Especially if this has been coordinated with /sys already :-)
